// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBSDyaKBLEWjdvYBUjB9U_GygHJkb_po',
    appId: '1:98198399231:android:620b77cabbb41d31b384ca',
    messagingSenderId: '98198399231',
    projectId: 'local-pulse-tanxr',
    storageBucket: 'local-pulse-tanxr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9sC9rZg0Z9_rHI4j4jIQa8P9zE9BKi6c',
    appId: '1:98198399231:ios:3ddb86ae05f9f110b384ca',
    messagingSenderId: '98198399231',
    projectId: 'local-pulse-tanxr',
    storageBucket: 'local-pulse-tanxr.firebasestorage.app',
    iosBundleId: 'ai.somethingtodo.somethingtodo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQlNzKOLjH0rFgT8K_2cGWJLNEQBUlXo',
    appId: '1:98198399231:web:3ddb86ae05f9f110b384ca',
    messagingSenderId: '98198399231',
    projectId: 'local-pulse-tanxr',
    authDomain: 'local-pulse-tanxr.firebaseapp.com',
    storageBucket: 'local-pulse-tanxr.firebasestorage.app',
  );
}
